
export const GET_FLIGHT_SEARCH_DATA = "GET_FLLIGHT_SEARCH_DATA";
export const GET_CITY_DATA = "GET_CITY_DATA";
export const GET_FLIGHT_DETAILS = "GET_FLIGHT_DETAILS";
export const PRICE_RANGE_FLIGHT_SEARCH = "PRICE_RANGE_FLIGHT_SEARCH";